### ISSUE TITLE
Итог проверки

### ISSUE THREAD

**Issue by XuMuK666** [Serg-ne-goreliy/Serg-ne-goreliy.github.io#2]
На предыдущее issues никак не прореагировал
Названия коммитов "." - это вообще не серьезно

Но, сайт неплохо отображается на мобильных устройствах, за это +1 балл

**Comment by Serg-ne-goreliy** [comment]
Спасибо))) а про коммиты я не знаю, я думал они не важны, ну возьму в учет в будущем

**Comment by Serg-ne-goreliy** [comment]
Спасибо))), а про комиты я не думал что их оригинальность так важна, ну на будущее учту
